#############################################################################
# Makefile for building: project_hzarrabi
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Nov 8 14:55:50 2014
# Project:  project_hzarrabi.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile project_hzarrabi.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Ilib -Iqt -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Movie.cpp \
		User.cpp \
		lib/main1.cpp \
		lib/Netflix.cpp \
		qt/displayWindow.cpp \
		qt/KeywordWindow.cpp \
		qt/LoginWindow.cpp \
		qt/NewUserWindow.cpp moc_displayWindow.cpp \
		moc_KeywordWindow.cpp \
		moc_LoginWindow.cpp \
		moc_NewUserWindow.cpp
OBJECTS       = Movie.o \
		User.o \
		main1.o \
		Netflix.o \
		displayWindow.o \
		KeywordWindow.o \
		LoginWindow.o \
		NewUserWindow.o \
		moc_displayWindow.o \
		moc_KeywordWindow.o \
		moc_LoginWindow.o \
		moc_NewUserWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		project_hzarrabi.pro
QMAKE_TARGET  = project_hzarrabi
DESTDIR       = 
TARGET        = project_hzarrabi

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: project_hzarrabi.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile project_hzarrabi.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile project_hzarrabi.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/project_hzarrabi1.0.0 || $(MKDIR) .tmp/project_hzarrabi1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/project_hzarrabi1.0.0/ && $(COPY_FILE) --parents Movie.h User.h lib/Map.h lib/map1.h lib/MergeSort.h lib/Netflix.h lib/Queue.h lib/queueImp.h lib/Set.h lib/set1.h qt/displayWindow.h qt/KeywordWindow.h qt/LoginWindow.h qt/NewUserWindow.h .tmp/project_hzarrabi1.0.0/ && $(COPY_FILE) --parents Movie.cpp User.cpp lib/main1.cpp lib/Netflix.cpp qt/displayWindow.cpp qt/KeywordWindow.cpp qt/LoginWindow.cpp qt/NewUserWindow.cpp .tmp/project_hzarrabi1.0.0/ && (cd `dirname .tmp/project_hzarrabi1.0.0` && $(TAR) project_hzarrabi1.0.0.tar project_hzarrabi1.0.0 && $(COMPRESS) project_hzarrabi1.0.0.tar) && $(MOVE) `dirname .tmp/project_hzarrabi1.0.0`/project_hzarrabi1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/project_hzarrabi1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_displayWindow.cpp moc_KeywordWindow.cpp moc_LoginWindow.cpp moc_NewUserWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_displayWindow.cpp moc_KeywordWindow.cpp moc_LoginWindow.cpp moc_NewUserWindow.cpp
moc_displayWindow.cpp: qt/KeywordWindow.h \
		qt/displayWindow.h \
		lib/Netflix.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h \
		qt/displayWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/displayWindow.h -o moc_displayWindow.cpp

moc_KeywordWindow.cpp: qt/displayWindow.h \
		qt/KeywordWindow.h \
		lib/Netflix.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h \
		qt/KeywordWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/KeywordWindow.h -o moc_KeywordWindow.cpp

moc_LoginWindow.cpp: qt/KeywordWindow.h \
		qt/displayWindow.h \
		lib/Netflix.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h \
		qt/NewUserWindow.h \
		qt/LoginWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/LoginWindow.h -o moc_LoginWindow.cpp

moc_NewUserWindow.cpp: lib/Netflix.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h \
		qt/NewUserWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qt/NewUserWindow.h -o moc_NewUserWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Movie.o: Movie.cpp Movie.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Movie.o Movie.cpp

User.o: User.cpp User.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/Queue.h \
		lib/queueImp.h \
		Movie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

main1.o: lib/main1.cpp lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h \
		lib/Netflix.h \
		qt/LoginWindow.h \
		qt/KeywordWindow.h \
		qt/displayWindow.h \
		qt/NewUserWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main1.o lib/main1.cpp

Netflix.o: lib/Netflix.cpp lib/Netflix.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Netflix.o lib/Netflix.cpp

displayWindow.o: qt/displayWindow.cpp qt/LoginWindow.h \
		qt/KeywordWindow.h \
		qt/displayWindow.h \
		lib/Netflix.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h \
		qt/NewUserWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o displayWindow.o qt/displayWindow.cpp

KeywordWindow.o: qt/KeywordWindow.cpp qt/KeywordWindow.h \
		qt/displayWindow.h \
		lib/Netflix.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KeywordWindow.o qt/KeywordWindow.cpp

LoginWindow.o: qt/LoginWindow.cpp qt/LoginWindow.h \
		qt/KeywordWindow.h \
		qt/displayWindow.h \
		lib/Netflix.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h \
		qt/NewUserWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoginWindow.o qt/LoginWindow.cpp

NewUserWindow.o: qt/NewUserWindow.cpp qt/NewUserWindow.h \
		lib/Netflix.h \
		lib/Set.h \
		lib/Map.h \
		lib/map1.h \
		lib/set1.h \
		lib/MergeSort.h \
		Movie.h \
		User.h \
		lib/Queue.h \
		lib/queueImp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NewUserWindow.o qt/NewUserWindow.cpp

moc_displayWindow.o: moc_displayWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_displayWindow.o moc_displayWindow.cpp

moc_KeywordWindow.o: moc_KeywordWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_KeywordWindow.o moc_KeywordWindow.cpp

moc_LoginWindow.o: moc_LoginWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoginWindow.o moc_LoginWindow.cpp

moc_NewUserWindow.o: moc_NewUserWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NewUserWindow.o moc_NewUserWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

