######################################################################
<<<<<<< HEAD
# Automatically generated by qmake (2.01a) Sat Dec 6 16:35:13 2014
=======
# Automatically generated by qmake (2.01a) Thu Dec 4 02:51:34 2014
>>>>>>> 87e48091298b8488cd29655c0d91f2bde374d47a
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . lib qt
INCLUDEPATH += . lib qt

# Input
HEADERS += Movie.h \
           User.h \
           lib/Map.h \
           lib/map1.h \
           lib/MergeSort.h \
           lib/Netflix.h \
           lib/Queue.h \
           lib/queueImp.h \
           lib/Set.h \
           lib/set1.h \
           qt/displayWindow.h \
           qt/KeywordWindow.h \
           qt/LoginWindow.h \
           qt/NewUserWindow.h \
           qt/RatingWindow.h
SOURCES += Movie.cpp \
           User.cpp \
           lib/main1.cpp \
           lib/Netflix.cpp \
           qt/displayWindow.cpp \
           qt/KeywordWindow.cpp \
           qt/LoginWindow.cpp \
           qt/NewUserWindow.cpp \
           qt/RatingWindow.cpp
