######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 6 22:29:19 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LoginWindow.h SignUpWindow.h
SOURCES += LoginWindow.cpp main.cpp SignUpWindow.cpp
